export const COUNTRIES = [
    {
      id: 'AF',
      name: 'Afghanistan',
      sortname: 'AF',
      phoneCode: '',
    },
    {
      id: 'AL',
      name: 'Albania',
      sortname: 'AL',
      phoneCode: '',
    },
    {
      id: 'DZ',
      name: 'Algeria',
      sortname: 'DZ',
      phoneCode: '',
    },
    {
      id: 'AS',
      name: 'American Samoa',
      sortname: 'AS',
      phoneCode: '',
    },
    {
      id: 'AD',
      name: 'Andorra',
      sortname: 'AD',
      phoneCode: '',
    },
    {
      id: 'AO',
      name: 'Angola',
      sortname: 'AO',
      phoneCode: '',
    },
    {
      id: 'AG',
      name: 'Antigua And Barbuda',
      sortname: 'AG',
      phoneCode: '',
    },
    {
      id: 'AR',
      name: 'Argentina',
      sortname: 'AR',
      phoneCode: '',
    },
    {
      id: 'AM',
      name: 'Armenia',
      sortname: 'AM',
      phoneCode: '',
    },
    {
      id: 'AW',
      name: 'Aruba',
      sortname: 'AW',
      phoneCode: '',
    },
    {
      id: 'AU',
      name: 'Australia',
      sortname: 'AU',
      phoneCode: '',
    },
    {
      id: 'AT',
      name: 'Austria',
      sortname: 'AT',
      phoneCode: '',
    },
    {
      id: 'AZ',
      name: 'Azerbaijan',
      sortname: 'AZ',
      phoneCode: '',
    },
    {
      id: 'BS',
      name: 'Bahamas, The',
      sortname: 'BS',
      phoneCode: '',
    },
    {
      id: 'BH',
      name: 'Bahrain',
      sortname: 'BH',
      phoneCode: '',
    },
    {
      id: 'BD',
      name: 'Bangladesh',
      sortname: 'BD',
      phoneCode: '',
    },
    {
      id: 'BB',
      name: 'Barbados',
      sortname: 'BB',
      phoneCode: '',
    },
    {
      id: 'BY',
      name: 'Belarus',
      sortname: 'BY',
      phoneCode: '',
    },
    {
      id: 'BE',
      name: 'Belgium',
      sortname: 'BE',
      phoneCode: '',
    },
    {
      id: 'BZ',
      name: 'Belize',
      sortname: 'BZ',
      phoneCode: '',
    },
    {
      id: 'BJ',
      name: 'Benin',
      sortname: 'BJ',
      phoneCode: '',
    },
    {
      id: 'BM',
      name: 'Bermuda',
      sortname: 'BM',
      phoneCode: '',
    },
    {
      id: 'BT',
      name: 'Bhutan',
      sortname: 'BT',
      phoneCode: '',
    },
    {
      id: 'BO',
      name: 'Bolivia',
      sortname: 'BO',
      phoneCode: '',
    },
    {
      id: 'BA',
      name: 'Bosnia And Herzegovina',
      sortname: 'BA',
      phoneCode: '',
    },
    {
      id: 'BW',
      name: 'Botswana',
      sortname: 'BW',
      phoneCode: '',
    },
    {
      id: 'BR',
      name: 'Brazil',
      sortname: 'BR',
      phoneCode: '',
    },
    {
      id: 'BN',
      name: 'Brunei',
      sortname: 'BN',
      phoneCode: '',
    },
    {
      id: 'BG',
      name: 'Bulgaria',
      sortname: 'BG',
      phoneCode: '',
    },
    {
      id: 'BF',
      name: 'Burkina Faso',
      sortname: 'BF',
      phoneCode: '',
    },
    {
      id: 'MM',
      name: 'Burma',
      sortname: 'MM',
      phoneCode: '',
    },
    {
      id: 'BI',
      name: 'Burundi',
      sortname: 'BI',
      phoneCode: '',
    },
    {
      id: 'CV',
      name: 'Cabo Verde',
      sortname: 'CV',
      phoneCode: '',
    },
    {
      id: 'KH',
      name: 'Cambodia',
      sortname: 'KH',
      phoneCode: '',
    },
    {
      id: 'CM',
      name: 'Cameroon',
      sortname: 'CM',
      phoneCode: '',
    },
    {
      id: 'CA',
      name: 'Canada',
      sortname: 'CA',
      phoneCode: '',
    },
    {
      id: 'KY',
      name: 'Cayman Islands',
      sortname: 'KY',
      phoneCode: '',
    },
    {
      id: 'CF',
      name: 'Central African Republic',
      sortname: 'CF',
      phoneCode: '',
    },
    {
      id: 'TD',
      name: 'Chad',
      sortname: 'TD',
      phoneCode: '',
    },
    {
      id: 'CL',
      name: 'Chile',
      sortname: 'CL',
      phoneCode: '',
    },
    {
      id: 'CN',
      name: 'China',
      sortname: 'CN',
      phoneCode: '',
    },
    {
      id: 'CO',
      name: 'Colombia',
      sortname: 'CO',
      phoneCode: '',
    },
    {
      id: 'KM',
      name: 'Comoros',
      sortname: 'KM',
      phoneCode: '',
    },
    {
      id: 'CG',
      name: 'Congo (Brazzaville)',
      sortname: 'CG',
      phoneCode: '',
    },
    {
      id: 'CD',
      name: 'Congo (Kinshasa)',
      sortname: 'CD',
      phoneCode: '',
    },
    {
      id: 'CK',
      name: 'Cook Islands',
      sortname: 'CK',
      phoneCode: '',
    },
    {
      id: 'CR',
      name: 'Costa Rica',
      sortname: 'CR',
      phoneCode: '',
    },
    {
      id: 'CI',
      name: 'C�te D�Ivoire',
      sortname: 'CI',
      phoneCode: '',
    },
    {
      id: 'iso2',
      name: 'country',
      sortname: 'iso2',
      phoneCode: '',
    },
    {
      id: 'HR',
      name: 'Croatia',
      sortname: 'HR',
      phoneCode: '',
    },
    {
      id: 'CU',
      name: 'Cuba',
      sortname: 'CU',
      phoneCode: '',
    },
    {
      id: 'CW',
      name: 'Cura�ao',
      sortname: 'CW',
      phoneCode: '',
    },
    {
      id: 'CY',
      name: 'Cyprus',
      sortname: 'CY',
      phoneCode: '',
    },
    {
      id: 'CZ',
      name: 'Czechia',
      sortname: 'CZ',
      phoneCode: '',
    },
    {
      id: 'DK',
      name: 'Denmark',
      sortname: 'DK',
      phoneCode: '',
    },
    {
      id: 'DJ',
      name: 'Djibouti',
      sortname: 'DJ',
      phoneCode: '',
    },
    {
      id: 'DM',
      name: 'Dominica',
      sortname: 'DM',
      phoneCode: '',
    },
    {
      id: 'DO',
      name: 'Dominican Republic',
      sortname: 'DO',
      phoneCode: '',
    },
    {
      id: 'EC',
      name: 'Ecuador',
      sortname: 'EC',
      phoneCode: '',
    },
    {
      id: 'EG',
      name: 'Egypt',
      sortname: 'EG',
      phoneCode: '',
    },
    {
      id: 'SV',
      name: 'El Salvador',
      sortname: 'SV',
      phoneCode: '',
    },
    {
      id: 'GQ',
      name: 'Equatorial Guinea',
      sortname: 'GQ',
      phoneCode: '',
    },
    {
      id: 'ER',
      name: 'Eritrea',
      sortname: 'ER',
      phoneCode: '',
    },
    {
      id: 'EE',
      name: 'Estonia',
      sortname: 'EE',
      phoneCode: '',
    },
    {
      id: 'ET',
      name: 'Ethiopia',
      sortname: 'ET',
      phoneCode: '',
    },
    {
      id: 'FK',
      name: 'Falkland Islands (Islas Malvinas)',
      sortname: 'FK',
      phoneCode: '',
    },
    {
      id: 'FO',
      name: 'Faroe Islands',
      sortname: 'FO',
      phoneCode: '',
    },
    {
      id: 'FJ',
      name: 'Fiji',
      sortname: 'FJ',
      phoneCode: '',
    },
    {
      id: 'FI',
      name: 'Finland',
      sortname: 'FI',
      phoneCode: '',
    },
    {
      id: 'FR',
      name: 'France',
      sortname: 'FR',
      phoneCode: '',
    },
    {
      id: 'GF',
      name: 'French Guiana',
      sortname: 'GF',
      phoneCode: '',
    },
    {
      id: 'PF',
      name: 'French Polynesia',
      sortname: 'PF',
      phoneCode: '',
    },
    {
      id: 'GA',
      name: 'Gabon',
      sortname: 'GA',
      phoneCode: '',
    },
    {
      id: 'GM',
      name: 'Gambia, The',
      sortname: 'GM',
      phoneCode: '',
    },
    {
      id: 'GE',
      name: 'Georgia',
      sortname: 'GE',
      phoneCode: '',
    },
    {
      id: 'DE',
      name: 'Germany',
      sortname: 'DE',
      phoneCode: '',
    },
    {
      id: 'GH',
      name: 'Ghana',
      sortname: 'GH',
      phoneCode: '',
    },
    {
      id: 'GI',
      name: 'Gibraltar',
      sortname: 'GI',
      phoneCode: '',
    },
    {
      id: 'GR',
      name: 'Greece',
      sortname: 'GR',
      phoneCode: '',
    },
    {
      id: 'GL',
      name: 'Greenland',
      sortname: 'GL',
      phoneCode: '',
    },
    {
      id: 'GD',
      name: 'Grenada',
      sortname: 'GD',
      phoneCode: '',
    },
    {
      id: 'GP',
      name: 'Guadeloupe',
      sortname: 'GP',
      phoneCode: '',
    },
    {
      id: 'GU',
      name: 'Guam',
      sortname: 'GU',
      phoneCode: '',
    },
    {
      id: 'GT',
      name: 'Guatemala',
      sortname: 'GT',
      phoneCode: '',
    },
    {
      id: 'GN',
      name: 'Guinea',
      sortname: 'GN',
      phoneCode: '',
    },
    {
      id: 'GW',
      name: 'Guinea-Bissau',
      sortname: 'GW',
      phoneCode: '',
    },
    {
      id: 'GY',
      name: 'Guyana',
      sortname: 'GY',
      phoneCode: '',
    },
    {
      id: 'HT',
      name: 'Haiti',
      sortname: 'HT',
      phoneCode: '',
    },
    {
      id: 'HN',
      name: 'Honduras',
      sortname: 'HN',
      phoneCode: '',
    },
    {
      id: 'HK',
      name: 'Hong Kong',
      sortname: 'HK',
      phoneCode: '',
    },
    {
      id: 'HU',
      name: 'Hungary',
      sortname: 'HU',
      phoneCode: '',
    },
    {
      id: 'IS',
      name: 'Iceland',
      sortname: 'IS',
      phoneCode: '',
    },
    {
      id: 'IN',
      name: 'India',
      sortname: 'IN',
      phoneCode: '',
    },
    {
      id: 'ID',
      name: 'Indonesia',
      sortname: 'ID',
      phoneCode: '',
    },
    {
      id: 'IR',
      name: 'Iran',
      sortname: 'IR',
      phoneCode: '',
    },
    {
      id: 'IQ',
      name: 'Iraq',
      sortname: 'IQ',
      phoneCode: '',
    },
    {
      id: 'IE',
      name: 'Ireland',
      sortname: 'IE',
      phoneCode: '',
    },
    {
      id: 'IM',
      name: 'Isle Of Man',
      sortname: 'IM',
      phoneCode: '',
    },
    {
      id: 'IL',
      name: 'Israel',
      sortname: 'IL',
      phoneCode: '',
    },
    {
      id: 'IT',
      name: 'Italy',
      sortname: 'IT',
      phoneCode: '',
    },
    {
      id: 'JM',
      name: 'Jamaica',
      sortname: 'JM',
      phoneCode: '',
    },
    {
      id: 'JP',
      name: 'Japan',
      sortname: 'JP',
      phoneCode: '',
    },
    {
      id: 'JO',
      name: 'Jordan',
      sortname: 'JO',
      phoneCode: '',
    },
    {
      id: 'KZ',
      name: 'Kazakhstan',
      sortname: 'KZ',
      phoneCode: '',
    },
    {
      id: 'KE',
      name: 'Kenya',
      sortname: 'KE',
      phoneCode: '',
    },
    {
      id: 'KI',
      name: 'Kiribati',
      sortname: 'KI',
      phoneCode: '',
    },
    {
      id: 'KP',
      name: 'Korea, North',
      sortname: 'KP',
      phoneCode: '',
    },
    {
      id: 'KR',
      name: 'Korea, South',
      sortname: 'KR',
      phoneCode: '',
    },
    {
      id: 'XK',
      name: 'Kosovo',
      sortname: 'XK',
      phoneCode: '',
    },
    {
      id: 'KW',
      name: 'Kuwait',
      sortname: 'KW',
      phoneCode: '',
    },
    {
      id: 'KG',
      name: 'Kyrgyzstan',
      sortname: 'KG',
      phoneCode: '',
    },
    {
      id: 'LA',
      name: 'Laos',
      sortname: 'LA',
      phoneCode: '',
    },
    {
      id: 'LV',
      name: 'Latvia',
      sortname: 'LV',
      phoneCode: '',
    },
    {
      id: 'LB',
      name: 'Lebanon',
      sortname: 'LB',
      phoneCode: '',
    },
    {
      id: 'LS',
      name: 'Lesotho',
      sortname: 'LS',
      phoneCode: '',
    },
    {
      id: 'LR',
      name: 'Liberia',
      sortname: 'LR',
      phoneCode: '',
    },
    {
      id: 'LY',
      name: 'Libya',
      sortname: 'LY',
      phoneCode: '',
    },
    {
      id: 'LI',
      name: 'Liechtenstein',
      sortname: 'LI',
      phoneCode: '',
    },
    {
      id: 'LT',
      name: 'Lithuania',
      sortname: 'LT',
      phoneCode: '',
    },
    {
      id: 'LU',
      name: 'Luxembourg',
      sortname: 'LU',
      phoneCode: '',
    },
    {
      id: 'MO',
      name: 'Macau',
      sortname: 'MO',
      phoneCode: '',
    },
    {
      id: 'MK',
      name: 'Macedonia',
      sortname: 'MK',
      phoneCode: '',
    },
    {
      id: 'MG',
      name: 'Madagascar',
      sortname: 'MG',
      phoneCode: '',
    },
    {
      id: 'MW',
      name: 'Malawi',
      sortname: 'MW',
      phoneCode: '',
    },
    {
      id: 'MY',
      name: 'Malaysia',
      sortname: 'MY',
      phoneCode: '',
    },
    {
      id: 'MV',
      name: 'Maldives',
      sortname: 'MV',
      phoneCode: '',
    },
    {
      id: 'ML',
      name: 'Mali',
      sortname: 'ML',
      phoneCode: '',
    },
    {
      id: 'MT',
      name: 'Malta',
      sortname: 'MT',
      phoneCode: '',
    },
    {
      id: 'MH',
      name: 'Marshall Islands',
      sortname: 'MH',
      phoneCode: '',
    },
    {
      id: 'MQ',
      name: 'Martinique',
      sortname: 'MQ',
      phoneCode: '',
    },
    {
      id: 'MR',
      name: 'Mauritania',
      sortname: 'MR',
      phoneCode: '',
    },
    {
      id: 'MU',
      name: 'Mauritius',
      sortname: 'MU',
      phoneCode: '',
    },
    {
      id: 'YT',
      name: 'Mayotte',
      sortname: 'YT',
      phoneCode: '',
    },
    {
      id: 'MX',
      name: 'Mexico',
      sortname: 'MX',
      phoneCode: '',
    },
    {
      id: 'FM',
      name: 'Micronesia, Federated States Of',
      sortname: 'FM',
      phoneCode: '',
    },
    {
      id: 'MD',
      name: 'Moldova',
      sortname: 'MD',
      phoneCode: '',
    },
    {
      id: 'MC',
      name: 'Monaco',
      sortname: 'MC',
      phoneCode: '',
    },
    {
      id: 'MN',
      name: 'Mongolia',
      sortname: 'MN',
      phoneCode: '',
    },
    {
      id: 'ME',
      name: 'Montenegro',
      sortname: 'ME',
      phoneCode: '',
    },
    {
      id: 'MA',
      name: 'Morocco',
      sortname: 'MA',
      phoneCode: '',
    },
    {
      id: 'MZ',
      name: 'Mozambique',
      sortname: 'MZ',
      phoneCode: '',
    },
    {
      id: 'NA',
      name: 'Namibia',
      sortname: 'NA',
      phoneCode: '',
    },
    {
      id: 'NP',
      name: 'Nepal',
      sortname: 'NP',
      phoneCode: '',
    },
    {
      id: 'NL',
      name: 'Netherlands',
      sortname: 'NL',
      phoneCode: '',
    },
    {
      id: 'NC',
      name: 'New Caledonia',
      sortname: 'NC',
      phoneCode: '',
    },
    {
      id: 'NZ',
      name: 'New Zealand',
      sortname: 'NZ',
      phoneCode: '',
    },
    {
      id: 'NI',
      name: 'Nicaragua',
      sortname: 'NI',
      phoneCode: '',
    },
    {
      id: 'NE',
      name: 'Niger',
      sortname: 'NE',
      phoneCode: '',
    },
    {
      id: 'NG',
      name: 'Nigeria',
      sortname: 'NG',
      phoneCode: '',
    },
    {
      id: 'MP',
      name: 'Northern Mariana Islands',
      sortname: 'MP',
      phoneCode: '',
    },
    {
      id: 'NO',
      name: 'Norway',
      sortname: 'NO',
      phoneCode: '',
    },
    {
      id: 'OM',
      name: 'Oman',
      sortname: 'OM',
      phoneCode: '',
    },
    {
      id: 'PK',
      name: 'Pakistan',
      sortname: 'PK',
      phoneCode: '',
    },
    {
      id: 'PW',
      name: 'Palau',
      sortname: 'PW',
      phoneCode: '',
    },
    {
      id: 'PA',
      name: 'Panama',
      sortname: 'PA',
      phoneCode: '',
    },
    {
      id: 'PG',
      name: 'Papua New Guinea',
      sortname: 'PG',
      phoneCode: '',
    },
    {
      id: 'PY',
      name: 'Paraguay',
      sortname: 'PY',
      phoneCode: '',
    },
    {
      id: 'PE',
      name: 'Peru',
      sortname: 'PE',
      phoneCode: '',
    },
    {
      id: 'PH',
      name: 'Philippines',
      sortname: 'PH',
      phoneCode: '',
    },
    {
      id: 'PL',
      name: 'Poland',
      sortname: 'PL',
      phoneCode: '',
    },
    {
      id: 'PT',
      name: 'Portugal',
      sortname: 'PT',
      phoneCode: '',
    },
    {
      id: 'PR',
      name: 'Puerto Rico',
      sortname: 'PR',
      phoneCode: '',
    },
    {
      id: 'QA',
      name: 'Qatar',
      sortname: 'QA',
      phoneCode: '',
    },
    {
      id: 'RE',
      name: 'Reunion',
      sortname: 'RE',
      phoneCode: '',
    },
    {
      id: 'RO',
      name: 'Romania',
      sortname: 'RO',
      phoneCode: '',
    },
    {
      id: 'RU',
      name: 'Russia',
      sortname: 'RU',
      phoneCode: '',
    },
    {
      id: 'RW',
      name: 'Rwanda',
      sortname: 'RW',
      phoneCode: '',
    },
    {
      id: 'SH',
      name: 'Saint Helena, Ascension, And Tristan Da Cunha',
      sortname: 'SH',
      phoneCode: '',
    },
    {
      id: 'KN',
      name: 'Saint Kitts And Nevis',
      sortname: 'KN',
      phoneCode: '',
    },
    {
      id: 'LC',
      name: 'Saint Lucia',
      sortname: 'LC',
      phoneCode: '',
    },
    {
      id: 'VC',
      name: 'Saint Vincent And The Grenadines',
      sortname: 'VC',
      phoneCode: '',
    },
    {
      id: 'WS',
      name: 'Samoa',
      sortname: 'WS',
      phoneCode: '',
    },
    {
      id: 'SM',
      name: 'San Marino',
      sortname: 'SM',
      phoneCode: '',
    },
    {
      id: 'ST',
      name: 'Sao Tome And Principe',
      sortname: 'ST',
      phoneCode: '',
    },
    {
      id: 'SA',
      name: 'Saudi Arabia',
      sortname: 'SA',
      phoneCode: '',
    },
    {
      id: 'SN',
      name: 'Senegal',
      sortname: 'SN',
      phoneCode: '',
    },
    {
      id: 'RS',
      name: 'Serbia',
      sortname: 'RS',
      phoneCode: '',
    },
    {
      id: 'SC',
      name: 'Seychelles',
      sortname: 'SC',
      phoneCode: '',
    },
    {
      id: 'SL',
      name: 'Sierra Leone',
      sortname: 'SL',
      phoneCode: '',
    },
    {
      id: 'SG',
      name: 'Singapore',
      sortname: 'SG',
      phoneCode: '',
    },
    {
      id: 'SX',
      name: 'Sint Maarten',
      sortname: 'SX',
      phoneCode: '',
    },
    {
      id: 'SK',
      name: 'Slovakia',
      sortname: 'SK',
      phoneCode: '',
    },
    {
      id: 'SI',
      name: 'Slovenia',
      sortname: 'SI',
      phoneCode: '',
    },
    {
      id: 'SB',
      name: 'Solomon Islands',
      sortname: 'SB',
      phoneCode: '',
    },
    {
      id: 'SO',
      name: 'Somalia',
      sortname: 'SO',
      phoneCode: '',
    },
    {
      id: 'ZA',
      name: 'South Africa',
      sortname: 'ZA',
      phoneCode: '',
    },
    {
      id: 'GS',
      name: 'South Georgia And South Sandwich Islands',
      sortname: 'GS',
      phoneCode: '',
    },
    {
      id: 'SS',
      name: 'South Sudan',
      sortname: 'SS',
      phoneCode: '',
    },
    {
      id: 'ES',
      name: 'Spain',
      sortname: 'ES',
      phoneCode: '',
    },
    {
      id: 'LK',
      name: 'Sri Lanka',
      sortname: 'LK',
      phoneCode: '',
    },
    {
      id: 'SD',
      name: 'Sudan',
      sortname: 'SD',
      phoneCode: '',
    },
    {
      id: 'SR',
      name: 'Suriname',
      sortname: 'SR',
      phoneCode: '',
    },
    {
      id: 'SZ',
      name: 'Swaziland',
      sortname: 'SZ',
      phoneCode: '',
    },
    {
      id: 'SE',
      name: 'Sweden',
      sortname: 'SE',
      phoneCode: '',
    },
    {
      id: 'CH',
      name: 'Switzerland',
      sortname: 'CH',
      phoneCode: '',
    },
    {
      id: 'SY',
      name: 'Syria',
      sortname: 'SY',
      phoneCode: '',
    },
    {
      id: 'TW',
      name: 'Taiwan',
      sortname: 'TW',
      phoneCode: '',
    },
    {
      id: 'TJ',
      name: 'Tajikistan',
      sortname: 'TJ',
      phoneCode: '',
    },
    {
      id: 'TZ',
      name: 'Tanzania',
      sortname: 'TZ',
      phoneCode: '',
    },
    {
      id: 'TH',
      name: 'Thailand',
      sortname: 'TH',
      phoneCode: '',
    },
    {
      id: 'TL',
      name: 'Timor-Leste',
      sortname: 'TL',
      phoneCode: '',
    },
    {
      id: 'TG',
      name: 'Togo',
      sortname: 'TG',
      phoneCode: '',
    },
    {
      id: 'TO',
      name: 'Tonga',
      sortname: 'TO',
      phoneCode: '',
    },
    {
      id: 'TT',
      name: 'Trinidad And Tobago',
      sortname: 'TT',
      phoneCode: '',
    },
    {
      id: 'TN',
      name: 'Tunisia',
      sortname: 'TN',
      phoneCode: '',
    },
    {
      id: 'TR',
      name: 'Turkey',
      sortname: 'TR',
      phoneCode: '',
    },
    {
      id: 'TM',
      name: 'Turkmenistan',
      sortname: 'TM',
      phoneCode: '',
    },
    {
      id: 'TC',
      name: 'Turks And Caicos Islands',
      sortname: 'TC',
      phoneCode: '',
    },
    {
      id: 'TV',
      name: 'Tuvalu',
      sortname: 'TV',
      phoneCode: '',
    },
    {
      id: 'UG',
      name: 'Uganda',
      sortname: 'UG',
      phoneCode: '',
    },
    {
      id: 'UA',
      name: 'Ukraine',
      sortname: 'UA',
      phoneCode: '',
    },
    {
      id: 'AE',
      name: 'United Arab Emirates',
      sortname: 'AE',
      phoneCode: '',
    },
    {
      id: 'GB',
      name: 'United Kingdom',
      sortname: 'GB',
      phoneCode: '',
    },
    {
      id: 'US',
      name: 'United States',
      sortname: 'US',
      phoneCode: '',
    },
    {
      id: 'UY',
      name: 'Uruguay',
      sortname: 'UY',
      phoneCode: '',
    },
    {
      id: 'UZ',
      name: 'Uzbekistan',
      sortname: 'UZ',
      phoneCode: '',
    },
    {
      id: 'VU',
      name: 'Vanuatu',
      sortname: 'VU',
      phoneCode: '',
    },
    {
      id: 'VE',
      name: 'Venezuela',
      sortname: 'VE',
      phoneCode: '',
    },
    {
      id: 'VN',
      name: 'Vietnam',
      sortname: 'VN',
      phoneCode: '',
    },
    {
      id: 'WF',
      name: 'Wallis And Futuna',
      sortname: 'WF',
      phoneCode: '',
    },
    {
      id: 'XW',
      name: 'West Bank',
      sortname: 'XW',
      phoneCode: '',
    },
    {
      id: 'YE',
      name: 'Yemen',
      sortname: 'YE',
      phoneCode: '',
    },
    {
      id: 'ZM',
      name: 'Zambia',
      sortname: 'ZM',
      phoneCode: '',
    },
    {
      id: 'ZW',
      name: 'Zimbabwe',
      sortname: 'ZW',
      phoneCode: '',
    },
  ];
  